mess with ci

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -2,8 +2,6 @@ name: Stg Build Deploy Payer API
 
 on:
   push:
-    branches:
-      - 'staging'
     tags:
       - '*'
 
@@ -14,23 +12,28 @@ jobs:
     steps:
       - uses: actions/checkout@v2.0.0
 
-      - name: Check git tag
-        run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
+      - name: Get staging commit sha
+        run: if [ $(git log -1 v0.1.0 --pretty=%H) == $(git rev-parse origin/staging) ]; then exit 0 ; else exit 1 ; fi
 
-      - name: Set to skip if no git tag
-        if: ${{ env.HEAD_TAG == '' }}
-        run: |
-          echo "$HEAD_TAG fail step because head of branch is not a tag"
-          echo "::set-output name=RUN_JOBS::false"
-      - name: Set to continue if tag exists
-        if: ${{ env.HEAD_TAG != '' }}
-        run: |
-          echo "$HEAD_TAG continue processing"
-          echo "::set-output name=RUN_JOBS::true"
+      # - name: Check git tag
+      #   run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
+
+      # - name: Get staging commit sha
+      #   run: echo "::set-env name=STAGING_SHA::$(git rev-parse origin/staging)"
+
+      # - name: Set to skip if no git tag
+      #   if: ${{ env.HEAD_TAG == '' }}
+      #   run: |
+      #     echo "$HEAD_TAG fail step because head of branch is not a tag"
+      #     echo "::set-output name=RUN_JOBS::false"
+      # - name: Set to continue if tag exists
+      #   if: ${{ env.HEAD_TAG != '' }}
+      #   run: |
+      #     echo "$HEAD_TAG continue processing"
+      #     echo "::set-output name=RUN_JOBS::true"
   build:
     runs-on: ubuntu-latest
-    if: outputs.RUN_JOBS == 'true'
-    # needs: [build-check]
+    needs: [build-check]
     steps:
       - name: run the build
         run: echo "build ran because tag found"
